name: Open TRS

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.10
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install package
          run: pip install .

        - name: Unit tests
          run: python -m unittest discover -s test