name: Open TRS

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
  FLASK_ENV: ci

jobs:
    test:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.10
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install package
          run: pip install . coverage pytest

        - name: Unit tests
          run: coverage run -m pytest